"""
Django settings for Bookshelf project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/ 
"""
"""
from pathlib import Path
import os 


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^i%c!8u(guor=z#@(=7$v8r2$f0qvs3g19v1)h54%t9#=p+jab'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.dev",   # يسمح بأي subdomain من ngrok-free.dev
    # لو أحياناً يطلع لك ngrok.io:
    ".ngrok.io",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework' ,
     'rest_framework.authtoken' ,
     'books' ,
     'accounts' ,
     'Home', 
     'dashboard',
     "corsheaders",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
         'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication', # المستخدم لازم يرسل token مع كل طلب
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # should login 
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'corsheaders.middleware.CorsMiddleware' ,
]

ROOT_URLCONF = 'Bookshelf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bookshelf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bookshelf',
        'USER': 'postgres',
        'PASSWORD': 'safwan123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/' 
MEDIA_ROOT = os.path.join( BASE_DIR , 'media') 

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    # لو بدك السماح لأي دومين ngrok عبر ريجكس:
    # "https://unlubricant-nonqualitative-colton.ngrok-free.dev",  # أو ريجكس أدناه
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok-free\.dev$",
]

# CORS_ALLOW_CREDENTIALS = True
# SESSION_COOKIE_SAMESITE = "None"
# SESSION_COOKIE_SECURE = True  # يحتاج https على الطرفين
# (نصيحة: خليك JWT/Token للتطوير أسهل)

CSRF_TRUSTED_ORIGINS = [
    "https://unlubricant-nonqualitative-colton.ngrok-free.dev",
]
"""

#Ali Altayar, [11/11/2025 12:59 م]
"""
Django settings for Bookshelf project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""


"""
from pathlib import Path
import os
from corsheaders.defaults import default_headers

# -----------------------------
# Paths
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# Security / Debug
# -----------------------------
SECRET_KEY = "django-insecure-^i%c!8u(guor=z#@(=7$v8r2$f0qvs3g19v1)h54%t9#=p+jab"
DEBUG = True

# إذا حابب تضيف الدومين الحالي نصيّاً:
NGROK_HOST = "unlubricant-nonqualitative-colton.ngrok-free.dev"  # عدّلها عندك إن حبيت

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.dev",   # أي subdomain من ngrok-free.dev
    ".ngrok.io",         # أحياناً ngrok.io
    # NGROK_HOST,        # اختياري: لو بدك تضيفه نصياً
]

# -----------------------------
# Applications
# -----------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # طرف ثالث
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    # تطبيقاتك
    "books",
    "accounts",
    "Home",
    "dashboard",
]

# -----------------------------
# REST Framework
# -----------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    # للتجريب فقط: اسمح لأي أحد يقرأ الـ APIs العامة (مثل /books/api/)
    # غيّرها لاحقاً إلى IsAuthenticated على قد الحاجة.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# -----------------------------
# Middleware (مهم: corsheaders قبل CommonMiddleware)
# -----------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    "corsheaders.middleware.CorsMiddleware",  # يجب أن يكون مبكراً
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------
# URLs / WSGI
# -----------------------------
ROOT_URLCONF = "Bookshelf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Bookshelf.wsgi.application"

# -----------------------------
# Database
# -----------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "bookshelf",
        "USER": "postgres",
        "PASSWORD": "safwan123",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# -----------------------------
# Password validation
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------
# i18n / TZ
# -----------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------
# Static / Media
# -----------------------------
STATIC_URL = "static/"

#Ali Altayar, [11/11/2025 12:59 م]
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -----------------------------
# CORS / CSRF (للعمل مع ngrok + Next.js)
# -----------------------------
# اسمح لـ localhost:3000 (تطوير Next.js)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    # بإمكانك إضافة الدومين النصّي أيضاً:
    # f"https://{NGROK_HOST}",
]

# Regex لأي دومين ngrok مجاني عبر HTTPS
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok-free\.dev$",
    r"^https://.*\.ngrok\.io$",
]

# لو تستخدم الهيدر الاختياري ngrok لتجاوز التحذير بدون كويري
CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

# لو بتستخدم CSRF مع جلسات عبر ngrok، لازم تضيف الدومين بالنص (لا يدعم regex)
CSRF_TRUSTED_ORIGINS = [
    f"https://{NGROK_HOST}",
]

# ملاحظة: يفضّل أثناء التطوير استخدام Token/JWT بدل الـ Cookies لتجنب تعقيدات CSRF.

# -----------------------------
# (اختياري) لو احتجت Django يعتبر الطلبات الآتية من ngrok على أنها HTTPS عند بناء روابط
# -----------------------------
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers
import dj_database_url

# -----------------------------
# Paths
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# Security / Debug
# -----------------------------
# نجيب القيم من متغيرات البيئة بدل ما تكون ثابتة في الكود

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret")

# الافتراضي True علشان التطوير، وفي السيرفر حط DJANGO_DEBUG=False
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# لو حابب تغيّر ngrok host من غير ما تعدل الكود، استخدم متغير بيئة
NGROK_HOST = os.environ.get(
    "NGROK_HOST",
    "unlubricant-nonqualitative-colton.ngrok-free.dev",  # القيمة القديمة كافتراضي
)

# ALLOWED_HOSTS من env مع قيمة افتراضية مفيدة للتطوير

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.dev",
    ".ngrok.io",
    ".railway.app",
    "web-production-7dcd.up.railway.app",  # الدومين الكامل تبع خدمتك
]


# -----------------------------
# Applications
# -----------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # طرف ثالث
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    # تطبيقاتك
    "books",
    "accounts",
    "Home",
    "dashboard",
]

# -----------------------------
# REST Framework
# -----------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# -----------------------------
# Middleware
# -----------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    "corsheaders.middleware.CorsMiddleware",  # يجب أن يكون مبكراً
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------
# URLs / WSGI
# -----------------------------
ROOT_URLCONF = "Bookshelf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Bookshelf.wsgi.application"

# -----------------------------
# Database
# -----------------------------
"""
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get(
            "DATABASE_URL",
            "postgres://postgres:safwan123@localhost:5432/bookshelf"
        ),
        conn_max_age=600,   # اختياري: لتحسين الأداء على السيرفر
    )
}
"""

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'PNefUvyKTPIrlghYQHxGGrXtNlxLSaaI',
        'HOST': 'postgres.railway.internal',
        'PORT': '5432',
    }
}
"""

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get(
            "DATABASE_URL",
            "postgres://postgres:safwan123@localhost:5432/bookshelf"
        ),
        conn_max_age=600,   # اختياري: لتحسين الأداء على السيرفر
    )
}

# -----------------------------
# Password validation
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------
# i18n / TZ
# -----------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------
# Static / Media
# -----------------------------
STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -----------------------------
# CORS / CSRF
# -----------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok-free\.dev$",
    r"^https://.*\.ngrok\.io$",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

CSRF_TRUSTED_ORIGINS = [
    f"https://{NGROK_HOST}",
]

# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")